# Raoul Scarazzini (rasca@mmul.it)
# Sample Dockerfile to test that the environment (docker or an orchestrator) is
# working correctly.

# Use the latest ubuntu container image to run everything
FROM ubuntu:latest

# Executes an infinite loop to print the date every 5 seconds
CMD bash -c "while true; do date; sleep 5; done"
